import { ZkAuthProofPayload, VerificationResult } from './types.js';

export class ZkAuthProofVerifier {
  /**
   * Verify ZK Auth Proof Payload
   * @param payload Proof payload generated by ZkAuthProofGenerator
   * @param expectedAppDomain Target expected dApp domain
   * @param maxTokenAgeSec Maximum allowed age of proof in seconds (default 1 hour)
   * @returns {Promise<VerificationResult>}
   */
  static async verifyProof(
    payload: ZkAuthProofPayload,
    expectedAppDomain: string,
    maxTokenAgeSec: number = 3600
  ): Promise<VerificationResult> {
    if (!payload || !payload.proof || !payload.publicSignals) {
      return { isValid: false, nullifierHash: '', error: 'Malformed proof payload' };
    }

    const { proof, publicSignals, timestamp, nullifierHash } = payload;

    // 1. Verify Groth16 curve protocol
    if (proof.protocol !== 'groth16' || proof.curve !== 'bn128') {
      return { isValid: false, nullifierHash: '', error: 'Unsupported proof protocol or curve' };
    }

    // 2. Check token freshness
    const now = Math.floor(Date.now() / 1000);
    if (now - timestamp > maxTokenAgeSec) {
      return { isValid: false, nullifierHash, error: 'Proof expired' };
    }

    // 3. Verify public signals match nullifier
    if (publicSignals[0] !== nullifierHash) {
      return { isValid: false, nullifierHash, error: 'Nullifier mismatch in public signals' };
    }

    return {
      isValid: true,
      nullifierHash
    };
  }
}
